
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class BattleLevelConfigCategory : Singleton<BattleLevelConfigCategory>, IConfig
    {
        private readonly Dictionary<int, BattleLevelConfig> _dataMap;
        private readonly List<BattleLevelConfig> _dataList;

        public BattleLevelConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, BattleLevelConfig>();
            _dataList = new List<BattleLevelConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                BattleLevelConfig _v;
                _v = global::ET.BattleLevelConfig.DeserializeBattleLevelConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, BattleLevelConfig> DataMap => _dataMap;
        public List<BattleLevelConfig> DataList => _dataList;

        public BattleLevelConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public BattleLevelConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
