
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BattlePassConfig : BeanBase
    {
        public BattlePassConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            RequiredLv = _buf.ReadInt();
            RewardItem1 = ExternalTypeUtil.NewRewardItem(global::ET.rewardItem.DeserializerewardItem(_buf));
            RewardItem2 = ExternalTypeUtil.NewRewardItem(global::ET.rewardItem.DeserializerewardItem(_buf));
            RewardItem3 = ExternalTypeUtil.NewRewardItem(global::ET.rewardItem.DeserializerewardItem(_buf));

            PostInit();
        }

        public static BattlePassConfig DeserializeBattlePassConfig(ByteBuf _buf)
        {
            return new BattlePassConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 获取奖励所需等级
        /// </summary>
        public readonly int RequiredLv;

        /// <summary>
        /// 奖励道具1
        /// </summary>
        public readonly ET.RewardItem RewardItem1;

        /// <summary>
        /// 奖励道具2
        /// </summary>
        public readonly ET.RewardItem RewardItem2;

        /// <summary>
        /// 奖励道具3
        /// </summary>
        public readonly ET.RewardItem RewardItem3;


        public const int __ID__ = 132296107;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "RequiredLv:" + RequiredLv + ","
            + "RewardItem1:" + RewardItem1 + ","
            + "RewardItem2:" + RewardItem2 + ","
            + "RewardItem3:" + RewardItem3 + ","
            + "}";
        }

        partial void PostInit();
    }
}
