
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BattleWaveConfig : BeanBase
    {
        public BattleWaveConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); MonsterBatchIds = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); MonsterBatchIds[__index0] = __e0;}}

            PostInit();
        }

        public static BattleWaveConfig DeserializeBattleWaveConfig(ByteBuf _buf)
        {
            return new BattleWaveConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 关卡名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 怪物批次 Id
        /// </summary>
        public readonly int[] MonsterBatchIds;


        public const int __ID__ = 150015635;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "MonsterBatchIds:" + Luban.StringUtil.CollectionToString(MonsterBatchIds) + ","
            + "}";
        }

        partial void PostInit();
    }
}
