
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class BattlePassConfigCategory : Singleton<BattlePassConfigCategory>, IConfig
    {
        private readonly Dictionary<int, BattlePassConfig> _dataMap;
        private readonly List<BattlePassConfig> _dataList;

        public BattlePassConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, BattlePassConfig>();
            _dataList = new List<BattlePassConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                BattlePassConfig _v;
                _v = global::ET.BattlePassConfig.DeserializeBattlePassConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, BattlePassConfig> DataMap => _dataMap;
        public List<BattlePassConfig> DataList => _dataList;

        public BattlePassConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public BattlePassConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
