
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class BuffConfigCategory : Singleton<BuffConfigCategory>, IConfig
    {
        private readonly Dictionary<int, BuffConfig> _dataMap;
        private readonly List<BuffConfig> _dataList;

        public BuffConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, BuffConfig>();
            _dataList = new List<BuffConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                BuffConfig _v;
                _v = global::ET.BuffConfig.DeserializeBuffConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, BuffConfig> DataMap => _dataMap;
        public List<BuffConfig> DataList => _dataList;

        public BuffConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public BuffConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
