
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class BuffConfig : BeanBase
    {
        public BuffConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            BuffName = _buf.ReadString();
            BuffTime = _buf.ReadInt();
            BuffDelayTime = _buf.ReadInt();
            TargetType = _buf.ReadInt();
            BuffBenefitType = _buf.ReadInt();
            BuffType = _buf.ReadInt();
            IsBuffStackable = _buf.ReadInt();
            BuffMaxStackCount = _buf.ReadInt();
            BuffParameterType = _buf.ReadInt();
            BuffParameterValue = _buf.ReadDouble();
            BuffEffectID = _buf.ReadInt();
            BuffDescribe = _buf.ReadString();

            PostInit();
        }

        public static BuffConfig DeserializeBuffConfig(ByteBuf _buf)
        {
            return new BuffConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 状态名称
        /// </summary>
        public readonly string BuffName;

        /// <summary>
        /// Buff存在时间
        /// </summary>
        public readonly int BuffTime;

        /// <summary>
        /// Buff延迟生效时间
        /// </summary>
        public readonly int BuffDelayTime;

        /// <summary>
        /// Buff目标类型
        /// </summary>
        public readonly int TargetType;

        /// <summary>
        /// Buff增益减益
        /// </summary>
        public readonly int BuffBenefitType;

        /// <summary>
        /// Buff类型
        /// </summary>
        public readonly int BuffType;

        /// <summary>
        /// Buff是否叠加
        /// </summary>
        public readonly int IsBuffStackable;

        /// <summary>
        /// Buff叠加层数上限
        /// </summary>
        public readonly int BuffMaxStackCount;

        /// <summary>
        /// Buff参数操作类型
        /// </summary>
        public readonly int BuffParameterType;

        /// <summary>
        /// Buff参数操作值
        /// </summary>
        public readonly double BuffParameterValue;

        /// <summary>
        /// Buff特效ID
        /// </summary>
        public readonly int BuffEffectID;

        /// <summary>
        /// Buff描述
        /// </summary>
        public readonly string BuffDescribe;


        public const int __ID__ = -1370631787;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "BuffName:" + BuffName + ","
            + "BuffTime:" + BuffTime + ","
            + "BuffDelayTime:" + BuffDelayTime + ","
            + "TargetType:" + TargetType + ","
            + "BuffBenefitType:" + BuffBenefitType + ","
            + "BuffType:" + BuffType + ","
            + "IsBuffStackable:" + IsBuffStackable + ","
            + "BuffMaxStackCount:" + BuffMaxStackCount + ","
            + "BuffParameterType:" + BuffParameterType + ","
            + "BuffParameterValue:" + BuffParameterValue + ","
            + "BuffEffectID:" + BuffEffectID + ","
            + "BuffDescribe:" + BuffDescribe + ","
            + "}";
        }

        partial void PostInit();
    }
}
