
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class DropConfig : BeanBase
    {
        public DropConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); DropItemInfos = new DropItemInfo[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { DropItemInfo __e0;__e0 = global::ET.DropItemInfo.DeserializeDropItemInfo(_buf); DropItemInfos[__index0] = __e0;}}

            PostInit();
        }

        public static DropConfig DeserializeDropConfig(ByteBuf _buf)
        {
            return new DropConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 掉落物
        /// </summary>
        public readonly DropItemInfo[] DropItemInfos;


        public const int __ID__ = -1845736655;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            foreach (var _e in DropItemInfos) { _e?.ResolveRef(); }
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "DropItemInfos:" + Luban.StringUtil.CollectionToString(DropItemInfos) + ","
            + "}";
        }

        partial void PostInit();
    }
}
