
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class EffectConfig : BeanBase
    {
        public EffectConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            EffectType = _buf.ReadInt();
            EffectName = _buf.ReadString();
            SkillEffectLiveTime = _buf.ReadFloat();
            SkillEffectDelayTime = _buf.ReadFloat();
            SkillParent = _buf.ReadInt();
            SkillParentPosition = _buf.ReadString();

            PostInit();
        }

        public static EffectConfig DeserializeEffectConfig(ByteBuf _buf)
        {
            return new EffectConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 特效类型
        /// </summary>
        public readonly int EffectType;

        /// <summary>
        /// 特效名称
        /// </summary>
        public readonly string EffectName;

        /// <summary>
        /// 技能特效存在时间
        /// </summary>
        public readonly float SkillEffectLiveTime;

        /// <summary>
        /// 技能特效延迟释放时间
        /// </summary>
        public readonly float SkillEffectDelayTime;

        /// <summary>
        /// 绑定父级
        /// </summary>
        public readonly int SkillParent;

        /// <summary>
        /// 绑定父级位置
        /// </summary>
        public readonly string SkillParentPosition;


        public const int __ID__ = -682668973;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "EffectType:" + EffectType + ","
            + "EffectName:" + EffectName + ","
            + "SkillEffectLiveTime:" + SkillEffectLiveTime + ","
            + "SkillEffectDelayTime:" + SkillEffectDelayTime + ","
            + "SkillParent:" + SkillParent + ","
            + "SkillParentPosition:" + SkillParentPosition + ","
            + "}";
        }

        partial void PostInit();
    }
}
