
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ItemConfig : BeanBase
    {
        public ItemConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ItemName = _buf.ReadString();
            Icon = _buf.ReadString();
            ItemQuality = _buf.ReadInt();
            UseLv = _buf.ReadInt();
            ItemType = (ItemType)_buf.ReadInt();
            ItemSubType = (ItemSubType)_buf.ReadInt();
            SellMoneyType = _buf.ReadInt();
            SellMoneyValue = _buf.ReadInt();
            ItemPileSum = _buf.ReadInt();
            ItemEquipID = _buf.ReadInt();
            ItemUsePar = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); ItemUseParInt = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); ItemUseParInt[__index0] = __e0;}}
            ItemDescription = _buf.ReadString();

            PostInit();
        }

        public static ItemConfig DeserializeItemConfig(ByteBuf _buf)
        {
            return new ItemConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 道具名称
        /// </summary>
        public readonly string ItemName;

        /// <summary>
        /// 道具Icon
        /// </summary>
        public readonly string Icon;

        /// <summary>
        /// 道具品质
        /// </summary>
        public readonly int ItemQuality;

        /// <summary>
        /// 使用等级
        /// </summary>
        public readonly int UseLv;

        /// <summary>
        /// 道具类型
        /// </summary>
        public readonly ItemType ItemType;

        /// <summary>
        /// 道具子类
        /// </summary>
        public readonly ItemSubType ItemSubType;

        /// <summary>
        /// 出售货币类型
        /// </summary>
        public readonly int SellMoneyType;

        /// <summary>
        /// 出售货币值
        /// </summary>
        public readonly int SellMoneyValue;

        /// <summary>
        /// 道具堆叠最大数量
        /// </summary>
        public readonly int ItemPileSum;

        /// <summary>
        /// 装备ID
        /// </summary>
        public readonly int ItemEquipID;

        /// <summary>
        /// 道具使用参数
        /// </summary>
        public readonly string ItemUsePar;

        /// <summary>
        /// 道具使用参数int
        /// </summary>
        public readonly int[] ItemUseParInt;

        /// <summary>
        /// 道具描述
        /// </summary>
        public readonly string ItemDescription;


        public const int __ID__ = -764023723;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ItemName:" + ItemName + ","
            + "Icon:" + Icon + ","
            + "ItemQuality:" + ItemQuality + ","
            + "UseLv:" + UseLv + ","
            + "ItemType:" + ItemType + ","
            + "ItemSubType:" + ItemSubType + ","
            + "SellMoneyType:" + SellMoneyType + ","
            + "SellMoneyValue:" + SellMoneyValue + ","
            + "ItemPileSum:" + ItemPileSum + ","
            + "ItemEquipID:" + ItemEquipID + ","
            + "ItemUsePar:" + ItemUsePar + ","
            + "ItemUseParInt:" + Luban.StringUtil.CollectionToString(ItemUseParInt) + ","
            + "ItemDescription:" + ItemDescription + ","
            + "}";
        }

        partial void PostInit();
    }
}
