
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MonsterBatchConfig : BeanBase
    {
        public MonsterBatchConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            DelayTime = _buf.ReadFloat();
            SpawnInterval = _buf.ReadFloat();
            SpawnNum = _buf.ReadInt();
            SpawnPosition = global::ET.vector2.Deserializevector2(_buf);
            MonsterId = _buf.ReadInt();

            PostInit();
        }

        public static MonsterBatchConfig DeserializeMonsterBatchConfig(ByteBuf _buf)
        {
            return new MonsterBatchConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 延迟出现时间
        /// </summary>
        public readonly float DelayTime;

        /// <summary>
        /// 刷新间隔
        /// </summary>
        public readonly float SpawnInterval;

        /// <summary>
        /// 生成几次
        /// </summary>
        public readonly int SpawnNum;

        /// <summary>
        /// 刷新位置
        /// </summary>
        public readonly vector2 SpawnPosition;

        /// <summary>
        /// 怪物Id
        /// </summary>
        public readonly int MonsterId;


        public const int __ID__ = -2027945214;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "DelayTime:" + DelayTime + ","
            + "SpawnInterval:" + SpawnInterval + ","
            + "SpawnNum:" + SpawnNum + ","
            + "SpawnPosition:" + SpawnPosition + ","
            + "MonsterId:" + MonsterId + ","
            + "}";
        }

        partial void PostInit();
    }
}
