
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MonsterBatchConfig : BeanBase
    {
        public MonsterBatchConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            SpawnTime = _buf.ReadFloat();
            SpawnPosition = ExternalTypeUtil.NewVector2(global::ET.vector2.Deserializevector2(_buf));
            MonsterId = _buf.ReadInt();

            PostInit();
        }

        public static MonsterBatchConfig DeserializeMonsterBatchConfig(ByteBuf _buf)
        {
            return new MonsterBatchConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 生成时间
        /// </summary>
        public readonly float SpawnTime;

        /// <summary>
        /// 生成位置
        /// </summary>
        public readonly System.Numerics.Vector2 SpawnPosition;

        /// <summary>
        /// 怪物Id
        /// </summary>
        public readonly int MonsterId;


        public const int __ID__ = -2027945214;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "SpawnTime:" + SpawnTime + ","
            + "SpawnPosition:" + SpawnPosition + ","
            + "MonsterId:" + MonsterId + ","
            + "}";
        }

        partial void PostInit();
    }
}
