
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MonsterConfig : BeanBase
    {
        public MonsterConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            MonsterName = _buf.ReadString();
            MonsterHeadIcon = _buf.ReadString();
            MonsterType = _buf.ReadInt();
            MonsterModelID = _buf.ReadInt();
            ChallengeTime = _buf.ReadInt();
            ActDistance = _buf.ReadInt();
            ActSkillID = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); SkillID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); SkillID[__index0] = __e0;}}
            Act = _buf.ReadInt();
            Def = _buf.ReadInt();
            Hp = _buf.ReadInt();
            AtkSpeed = _buf.ReadDouble();
            MoveSpeed = _buf.ReadDouble();
            Cri = _buf.ReadDouble();
            MonsterDescription = _buf.ReadString();

            PostInit();
        }

        public static MonsterConfig DeserializeMonsterConfig(ByteBuf _buf)
        {
            return new MonsterConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 怪物名称
        /// </summary>
        public readonly string MonsterName;

        /// <summary>
        /// 怪物头像
        /// </summary>
        public readonly string MonsterHeadIcon;

        /// <summary>
        /// 怪物类型
        /// </summary>
        public readonly int MonsterType;

        /// <summary>
        /// 怪物模型ID
        /// </summary>
        public readonly int MonsterModelID;

        /// <summary>
        /// 怪物挑战时间[秒]
        /// </summary>
        public readonly int ChallengeTime;

        /// <summary>
        /// 攻击距离
        /// </summary>
        public readonly int ActDistance;

        /// <summary>
        /// 普通攻击ID
        /// </summary>
        public readonly int ActSkillID;

        /// <summary>
        /// 怪物技能ID
        /// </summary>
        public readonly int[] SkillID;

        /// <summary>
        /// 攻击
        /// </summary>
        public readonly int Act;

        /// <summary>
        /// 防御
        /// </summary>
        public readonly int Def;

        /// <summary>
        /// 生命
        /// </summary>
        public readonly int Hp;

        /// <summary>
        /// 攻速
        /// </summary>
        public readonly double AtkSpeed;

        /// <summary>
        /// 移速
        /// </summary>
        public readonly double MoveSpeed;

        /// <summary>
        /// 暴击概率
        /// </summary>
        public readonly double Cri;

        /// <summary>
        /// 怪物简介
        /// </summary>
        public readonly string MonsterDescription;


        public const int __ID__ = -55174244;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "MonsterName:" + MonsterName + ","
            + "MonsterHeadIcon:" + MonsterHeadIcon + ","
            + "MonsterType:" + MonsterType + ","
            + "MonsterModelID:" + MonsterModelID + ","
            + "ChallengeTime:" + ChallengeTime + ","
            + "ActDistance:" + ActDistance + ","
            + "ActSkillID:" + ActSkillID + ","
            + "SkillID:" + Luban.StringUtil.CollectionToString(SkillID) + ","
            + "Act:" + Act + ","
            + "Def:" + Def + ","
            + "Hp:" + Hp + ","
            + "AtkSpeed:" + AtkSpeed + ","
            + "MoveSpeed:" + MoveSpeed + ","
            + "Cri:" + Cri + ","
            + "MonsterDescription:" + MonsterDescription + ","
            + "}";
        }

        partial void PostInit();
    }
}
