
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class NPCConfigCategory : Singleton<NPCConfigCategory>, IConfig
    {
        private readonly Dictionary<int, NPCConfig> _dataMap;
        private readonly List<NPCConfig> _dataList;

        public NPCConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, NPCConfig>();
            _dataList = new List<NPCConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                NPCConfig _v;
                _v = global::ET.NPCConfig.DeserializeNPCConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, NPCConfig> DataMap => _dataMap;
        public List<NPCConfig> DataList => _dataList;

        public NPCConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public NPCConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
