
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class RechargePointsRewardConfig : BeanBase
    {
        public RechargePointsRewardConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            RequiredPoints = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); RewardItem = new ET.RewardItem[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { ET.RewardItem __e0;__e0 = ExternalTypeUtil.NewRewardItem(global::ET.rewardItem.DeserializerewardItem(_buf)); RewardItem[__index0] = __e0;}}

            PostInit();
        }

        public static RechargePointsRewardConfig DeserializeRechargePointsRewardConfig(ByteBuf _buf)
        {
            return new RechargePointsRewardConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 获取奖励所需积分
        /// </summary>
        public readonly int RequiredPoints;

        /// <summary>
        /// 奖励道具
        /// </summary>
        public readonly ET.RewardItem[] RewardItem;


        public const int __ID__ = -1639190789;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "RequiredPoints:" + RequiredPoints + ","
            + "RewardItem:" + Luban.StringUtil.CollectionToString(RewardItem) + ","
            + "}";
        }

        partial void PostInit();
    }
}
