
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class RechargeConfig : BeanBase
    {
        public RechargeConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Type = _buf.ReadInt();
            Price = _buf.ReadInt();
            Diamond = _buf.ReadInt();
            Point = _buf.ReadInt();

            PostInit();
        }

        public static RechargeConfig DeserializeRechargeConfig(ByteBuf _buf)
        {
            return new RechargeConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 货币类型
        /// </summary>
        public readonly int Type;

        /// <summary>
        /// 价格
        /// </summary>
        public readonly int Price;

        /// <summary>
        /// 钻石
        /// </summary>
        public readonly int Diamond;

        /// <summary>
        /// 积分
        /// </summary>
        public readonly int Point;


        public const int __ID__ = -1565007639;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Type:" + Type + ","
            + "Price:" + Price + ","
            + "Diamond:" + Diamond + ","
            + "Point:" + Point + ","
            + "}";
        }

        partial void PostInit();
    }
}
