
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ServerOpenRewardConfig : BeanBase
    {
        public ServerOpenRewardConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            RequiredType = _buf.ReadInt();
            RequiredValue = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); RewardItem = new ET.RewardItem[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { ET.RewardItem __e0;__e0 = ExternalTypeUtil.NewRewardItem(global::ET.rewardItem.DeserializerewardItem(_buf)); RewardItem[__index0] = __e0;}}

            PostInit();
        }

        public static ServerOpenRewardConfig DeserializeServerOpenRewardConfig(ByteBuf _buf)
        {
            return new ServerOpenRewardConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 要求类型
        /// </summary>
        public readonly int RequiredType;

        /// <summary>
        /// 要求值
        /// </summary>
        public readonly int RequiredValue;

        /// <summary>
        /// 奖励道具
        /// </summary>
        public readonly ET.RewardItem[] RewardItem;


        public const int __ID__ = -597822402;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "RequiredType:" + RequiredType + ","
            + "RequiredValue:" + RequiredValue + ","
            + "RewardItem:" + Luban.StringUtil.CollectionToString(RewardItem) + ","
            + "}";
        }

        partial void PostInit();
    }
}
