
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class ServerOpenRewardConfigCategory : Singleton<ServerOpenRewardConfigCategory>, IConfig
    {
        private readonly Dictionary<int, ServerOpenRewardConfig> _dataMap;
        private readonly List<ServerOpenRewardConfig> _dataList;

        public ServerOpenRewardConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ServerOpenRewardConfig>();
            _dataList = new List<ServerOpenRewardConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ServerOpenRewardConfig _v;
                _v = global::ET.ServerOpenRewardConfig.DeserializeServerOpenRewardConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ServerOpenRewardConfig> DataMap => _dataMap;
        public List<ServerOpenRewardConfig> DataList => _dataList;

        public ServerOpenRewardConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public ServerOpenRewardConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
