
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SkillConfig : BeanBase
    {
        public SkillConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            SkillName = _buf.ReadString();
            SkillIcon = _buf.ReadString();
            SkillActType = _buf.ReadInt();
            SkillHandler = _buf.ReadString();
            SkillCD = _buf.ReadDouble();
            SkillLiveTime = _buf.ReadInt();
            DamgeValue = _buf.ReadInt();
            SkillAnimation = _buf.ReadString();
            SkillHitEffectID = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); BuffID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); BuffID[__index0] = __e0;}}
            SkillMusic = _buf.ReadString();
            SkillDescribe = _buf.ReadString();

            PostInit();
        }

        public static SkillConfig DeserializeSkillConfig(ByteBuf _buf)
        {
            return new SkillConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 技能名称
        /// </summary>
        public readonly string SkillName;

        /// <summary>
        /// 技能Icon
        /// </summary>
        public readonly string SkillIcon;

        /// <summary>
        /// 技能攻击类型
        /// </summary>
        public readonly int SkillActType;

        /// <summary>
        /// 脚本名称
        /// </summary>
        public readonly string SkillHandler;

        /// <summary>
        /// 技能CD
        /// </summary>
        public readonly double SkillCD;

        /// <summary>
        /// 技能存在时间[毫秒]
        /// </summary>
        public readonly int SkillLiveTime;

        /// <summary>
        /// 固定伤害值
        /// </summary>
        public readonly int DamgeValue;

        /// <summary>
        /// 施法动作名称
        /// </summary>
        public readonly string SkillAnimation;

        /// <summary>
        /// 技能特效Id
        /// </summary>
        public readonly int SkillHitEffectID;

        /// <summary>
        /// 释放BUFFID
        /// </summary>
        public readonly int[] BuffID;

        /// <summary>
        /// 技能音效
        /// </summary>
        public readonly string SkillMusic;

        /// <summary>
        /// 技能描述
        /// </summary>
        public readonly string SkillDescribe;


        public const int __ID__ = -844226349;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "SkillName:" + SkillName + ","
            + "SkillIcon:" + SkillIcon + ","
            + "SkillActType:" + SkillActType + ","
            + "SkillHandler:" + SkillHandler + ","
            + "SkillCD:" + SkillCD + ","
            + "SkillLiveTime:" + SkillLiveTime + ","
            + "DamgeValue:" + DamgeValue + ","
            + "SkillAnimation:" + SkillAnimation + ","
            + "SkillHitEffectID:" + SkillHitEffectID + ","
            + "BuffID:" + Luban.StringUtil.CollectionToString(BuffID) + ","
            + "SkillMusic:" + SkillMusic + ","
            + "SkillDescribe:" + SkillDescribe + ","
            + "}";
        }

        partial void PostInit();
    }
}
