
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SkillConfig : BeanBase
    {
        public SkillConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            SkillName = _buf.ReadString();
            SkillIcon = _buf.ReadString();
            SkillActType = _buf.ReadInt();
            DamageType = _buf.ReadInt();
            SkillAddAnger = _buf.ReadInt();
            SkillHandler = _buf.ReadString();
            GameObjectParameter = _buf.ReadString();
            UnlockStar = _buf.ReadInt();
            SkillType = _buf.ReadInt();
            PassiveSkillType = _buf.ReadInt();
            PassiveSkillPro = _buf.ReadDouble();
            PassiveSkillTriggerOnce = _buf.ReadInt();
            SkillCD = _buf.ReadDouble();
            SkillLiveTime = _buf.ReadFloat();
            ActDamage = _buf.ReadDouble();
            DamgeValue = _buf.ReadInt();
            SkillAnimation = _buf.ReadString();
            SkillMusic = _buf.ReadString();
            SkillTargetType = (SkillTargetType)_buf.ReadInt();
            DamageRangeType = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); DamageRange = new float[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { float __e0;__e0 = _buf.ReadFloat(); DamageRange[__index0] = __e0;}}
            Speed = _buf.ReadFloat();
            SkillEffectID = _buf.ReadInt();
            SkillHitEffectID = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); InitBuffID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); InitBuffID[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); BuffID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); BuffID[__index0] = __e0;}}
            SkillDescribe = _buf.ReadString();

            PostInit();
        }

        public static SkillConfig DeserializeSkillConfig(ByteBuf _buf)
        {
            return new SkillConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 技能名称
        /// </summary>
        public readonly string SkillName;

        /// <summary>
        /// 技能Icon
        /// </summary>
        public readonly string SkillIcon;

        /// <summary>
        /// 技能攻击类型
        /// </summary>
        public readonly int SkillActType;

        /// <summary>
        /// 伤害类型
        /// </summary>
        public readonly int DamageType;

        /// <summary>
        /// 增加怒气值
        /// </summary>
        public readonly int SkillAddAnger;

        /// <summary>
        /// 脚本名称
        /// </summary>
        public readonly string SkillHandler;

        /// <summary>
        /// 脚本参数
        /// </summary>
        public readonly string GameObjectParameter;

        /// <summary>
        /// 解锁星级
        /// </summary>
        public readonly int UnlockStar;

        /// <summary>
        /// 技能类型
        /// </summary>
        public readonly int SkillType;

        /// <summary>
        /// 被动技能触发类型
        /// </summary>
        public readonly int PassiveSkillType;

        /// <summary>
        /// 被动技能触发参数
        /// </summary>
        public readonly double PassiveSkillPro;

        /// <summary>
        /// 被动技能触发一次
        /// </summary>
        public readonly int PassiveSkillTriggerOnce;

        /// <summary>
        /// 技能CD
        /// </summary>
        public readonly double SkillCD;

        /// <summary>
        /// 技能存在时间
        /// </summary>
        public readonly float SkillLiveTime;

        /// <summary>
        /// 攻击系数
        /// </summary>
        public readonly double ActDamage;

        /// <summary>
        /// 固定伤害值
        /// </summary>
        public readonly int DamgeValue;

        /// <summary>
        /// 施法动作名称
        /// </summary>
        public readonly string SkillAnimation;

        /// <summary>
        /// 技能音效
        /// </summary>
        public readonly string SkillMusic;

        /// <summary>
        /// 技能目标类型
        /// </summary>
        public readonly SkillTargetType SkillTargetType;

        /// <summary>
        /// 伤害范围类型
        /// </summary>
        public readonly int DamageRangeType;

        /// <summary>
        /// 伤害范围
        /// </summary>
        public readonly float[] DamageRange;

        /// <summary>
        /// 速度
        /// </summary>
        public readonly float Speed;

        /// <summary>
        /// 技能特效Id
        /// </summary>
        public readonly int SkillEffectID;

        /// <summary>
        /// 技能命中特效Id
        /// </summary>
        public readonly int SkillHitEffectID;

        /// <summary>
        /// 初始化BUFFID
        /// </summary>
        public readonly int[] InitBuffID;

        /// <summary>
        /// 释放BUFFID
        /// </summary>
        public readonly int[] BuffID;

        /// <summary>
        /// 技能描述
        /// </summary>
        public readonly string SkillDescribe;


        public const int __ID__ = -844226349;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "SkillName:" + SkillName + ","
            + "SkillIcon:" + SkillIcon + ","
            + "SkillActType:" + SkillActType + ","
            + "DamageType:" + DamageType + ","
            + "SkillAddAnger:" + SkillAddAnger + ","
            + "SkillHandler:" + SkillHandler + ","
            + "GameObjectParameter:" + GameObjectParameter + ","
            + "UnlockStar:" + UnlockStar + ","
            + "SkillType:" + SkillType + ","
            + "PassiveSkillType:" + PassiveSkillType + ","
            + "PassiveSkillPro:" + PassiveSkillPro + ","
            + "PassiveSkillTriggerOnce:" + PassiveSkillTriggerOnce + ","
            + "SkillCD:" + SkillCD + ","
            + "SkillLiveTime:" + SkillLiveTime + ","
            + "ActDamage:" + ActDamage + ","
            + "DamgeValue:" + DamgeValue + ","
            + "SkillAnimation:" + SkillAnimation + ","
            + "SkillMusic:" + SkillMusic + ","
            + "SkillTargetType:" + SkillTargetType + ","
            + "DamageRangeType:" + DamageRangeType + ","
            + "DamageRange:" + Luban.StringUtil.CollectionToString(DamageRange) + ","
            + "Speed:" + Speed + ","
            + "SkillEffectID:" + SkillEffectID + ","
            + "SkillHitEffectID:" + SkillHitEffectID + ","
            + "InitBuffID:" + Luban.StringUtil.CollectionToString(InitBuffID) + ","
            + "BuffID:" + Luban.StringUtil.CollectionToString(BuffID) + ","
            + "SkillDescribe:" + SkillDescribe + ","
            + "}";
        }

        partial void PostInit();
    }
}
