
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class StoreItemConfig : BeanBase
    {
        public StoreItemConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            SellItemID = _buf.ReadInt();
            SellType = _buf.ReadInt();
            SellValue = _buf.ReadInt();
            LimitNumber = _buf.ReadInt();

            PostInit();
        }

        public static StoreItemConfig DeserializeStoreItemConfig(ByteBuf _buf)
        {
            return new StoreItemConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 出售道具ID
        /// </summary>
        public readonly int SellItemID;

        /// <summary>
        /// 出售货币种类
        /// </summary>
        public readonly int SellType;

        /// <summary>
        /// 出售价格
        /// </summary>
        public readonly int SellValue;

        /// <summary>
        /// 限购次数
        /// </summary>
        public readonly int LimitNumber;


        public const int __ID__ = -482428970;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "SellItemID:" + SellItemID + ","
            + "SellType:" + SellType + ","
            + "SellValue:" + SellValue + ","
            + "LimitNumber:" + LimitNumber + ","
            + "}";
        }

        partial void PostInit();
    }
}
