
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class WaveConfigCategory : Singleton<WaveConfigCategory>, IConfig
    {
        private readonly Dictionary<int, WaveConfig> _dataMap;
        private readonly List<WaveConfig> _dataList;

        public WaveConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, WaveConfig>();
            _dataList = new List<WaveConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                WaveConfig _v;
                _v = global::ET.WaveConfig.DeserializeWaveConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, WaveConfig> DataMap => _dataMap;
        public List<WaveConfig> DataList => _dataList;

        public WaveConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public WaveConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
