
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 成就目标类型
    /// </summary>
    public enum AchievementTargetType
    {
        None = 0,

        /// <summary>
        /// 拥有指定英雄
        /// </summary>
        HaveHeroId = 1,

        /// <summary>
        /// 拥有英雄数量
        /// </summary>
        HaveHeroValue = 2,

        /// <summary>
        /// 英雄最高等级
        /// </summary>
        HeroLv = 3,

    }
}
