
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class AchievementConfig : BeanBase
    {
        public AchievementConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            RewardPoints = _buf.ReadInt();
            AchievementTargetType = (AchievementTargetType)_buf.ReadInt();
            TargetID = _buf.ReadInt();
            TargetValue = _buf.ReadInt();
            Description = _buf.ReadString();

            PostInit();
        }

        public static AchievementConfig DeserializeAchievementConfig(ByteBuf _buf)
        {
            return new AchievementConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 成就名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 奖励成就点
        /// </summary>
        public readonly int RewardPoints;

        /// <summary>
        /// 目标要求类型
        /// </summary>
        public readonly AchievementTargetType AchievementTargetType;

        /// <summary>
        /// 目标要求ID
        /// </summary>
        public readonly int TargetID;

        /// <summary>
        /// 目标要求值
        /// </summary>
        public readonly int TargetValue;

        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Description;


        public const int __ID__ = -714023119;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "RewardPoints:" + RewardPoints + ","
            + "AchievementTargetType:" + AchievementTargetType + ","
            + "TargetID:" + TargetID + ","
            + "TargetValue:" + TargetValue + ","
            + "Description:" + Description + ","
            + "}";
        }

        partial void PostInit();
    }
}
