
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class AchievementRewardConfigCategory : Singleton<AchievementRewardConfigCategory>, IConfig
    {
        private readonly Dictionary<int, AchievementRewardConfig> _dataMap;
        private readonly List<AchievementRewardConfig> _dataList;

        public AchievementRewardConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, AchievementRewardConfig>();
            _dataList = new List<AchievementRewardConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                AchievementRewardConfig _v;
                _v = global::ET.AchievementRewardConfig.DeserializeAchievementRewardConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, AchievementRewardConfig> DataMap => _dataMap;
        public List<AchievementRewardConfig> DataList => _dataList;

        public AchievementRewardConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public AchievementRewardConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
