
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class ArchiveRewardConfigCategory : Singleton<ArchiveRewardConfigCategory>, IConfig
    {
        private readonly Dictionary<int, ArchiveRewardConfig> _dataMap;
        private readonly List<ArchiveRewardConfig> _dataList;

        public ArchiveRewardConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, ArchiveRewardConfig>();
            _dataList = new List<ArchiveRewardConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                ArchiveRewardConfig _v;
                _v = global::ET.ArchiveRewardConfig.DeserializeArchiveRewardConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, ArchiveRewardConfig> DataMap => _dataMap;
        public List<ArchiveRewardConfig> DataList => _dataList;

        public ArchiveRewardConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public ArchiveRewardConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
