
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class DropItemInfo : BeanBase
    {
        public DropItemInfo(ByteBuf _buf)
        {
            Weight = _buf.ReadInt();
            ItemId = _buf.ReadInt();
            MinNum = _buf.ReadInt();
            MaxNum = _buf.ReadInt();

            PostInit();
        }

        public static DropItemInfo DeserializeDropItemInfo(ByteBuf _buf)
        {
            return new DropItemInfo(_buf);
        }

        /// <summary>
        /// 权重
        /// </summary>
        public readonly int Weight;

        /// <summary>
        /// 道具配置Id
        /// </summary>
        public readonly int ItemId;

        public readonly int MinNum;

        public readonly int MaxNum;


        public const int __ID__ = 1825905296;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Weight:" + Weight + ","
            + "ItemId:" + ItemId + ","
            + "MinNum:" + MinNum + ","
            + "MaxNum:" + MaxNum + ","
            + "}";
        }

        partial void PostInit();
    }
}
