
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class EquipConfig : BeanBase
    {
        public EquipConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ItemName = _buf.ReadString();
            {int n0 = _buf.ReadSize(); HideType = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); HideType.Add(_e0);}}
            HideShowPro = _buf.ReadDouble();
            {int n0 = _buf.ReadSize(); SellResourcesType = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); SellResourcesType.Add(_e0);}}
            {int n0 = _buf.ReadSize(); SellResourcesValue = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); SellResourcesValue.Add(_e0);}}
            EquipMinAct = _buf.ReadInt();
            EquipMaxAct = _buf.ReadInt();
            EquipMinDef = _buf.ReadInt();
            EquipMaxDef = _buf.ReadInt();
            EquipMinAdf = _buf.ReadInt();
            EquipMaxAdf = _buf.ReadInt();
            EquipHp = _buf.ReadInt();
            EquipAtkSpeed = _buf.ReadLong();
            EquipMoveSpeed = _buf.ReadLong();
            EquipCri = _buf.ReadLong();
            EquipCombo = _buf.ReadLong();
            EquipCounterattack = _buf.ReadLong();
            EquipLifeSteal = _buf.ReadLong();
            EquipEva = _buf.ReadLong();
            EquipReCri = _buf.ReadLong();
            EquipReCombo = _buf.ReadLong();
            EquipReCounterattack = _buf.ReadLong();
            EquipReLifeSteal = _buf.ReadLong();
            EquipReEva = _buf.ReadLong();

            PostInit();
        }

        public static EquipConfig DeserializeEquipConfig(ByteBuf _buf)
        {
            return new EquipConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 装备名称
        /// </summary>
        public readonly string ItemName;

        /// <summary>
        /// 隐藏属性类型
        /// </summary>
        public readonly System.Collections.Generic.List<int> HideType;

        /// <summary>
        /// 单条隐藏属性出现概率
        /// </summary>
        public readonly double HideShowPro;

        /// <summary>
        /// 分解资源类型
        /// </summary>
        public readonly System.Collections.Generic.List<int> SellResourcesType;

        /// <summary>
        /// 分解资源值
        /// </summary>
        public readonly System.Collections.Generic.List<int> SellResourcesValue;

        /// <summary>
        /// 最低攻击
        /// </summary>
        public readonly int EquipMinAct;

        /// <summary>
        /// 最高攻击
        /// </summary>
        public readonly int EquipMaxAct;

        /// <summary>
        /// 最低防御
        /// </summary>
        public readonly int EquipMinDef;

        /// <summary>
        /// 最高防御
        /// </summary>
        public readonly int EquipMaxDef;

        /// <summary>
        /// 最低魔防
        /// </summary>
        public readonly int EquipMinAdf;

        /// <summary>
        /// 最高魔防
        /// </summary>
        public readonly int EquipMaxAdf;

        /// <summary>
        /// 生命
        /// </summary>
        public readonly int EquipHp;

        /// <summary>
        /// 攻速
        /// </summary>
        public readonly long EquipAtkSpeed;

        /// <summary>
        /// 移速
        /// </summary>
        public readonly long EquipMoveSpeed;

        /// <summary>
        /// 暴击
        /// </summary>
        public readonly long EquipCri;

        /// <summary>
        /// 连击
        /// </summary>
        public readonly long EquipCombo;

        /// <summary>
        /// 反击
        /// </summary>
        public readonly long EquipCounterattack;

        /// <summary>
        /// 吸血
        /// </summary>
        public readonly long EquipLifeSteal;

        /// <summary>
        /// 闪避
        /// </summary>
        public readonly long EquipEva;

        /// <summary>
        /// 抗暴击
        /// </summary>
        public readonly long EquipReCri;

        /// <summary>
        /// 抗连击
        /// </summary>
        public readonly long EquipReCombo;

        /// <summary>
        /// 抗反击
        /// </summary>
        public readonly long EquipReCounterattack;

        /// <summary>
        /// 抗吸血
        /// </summary>
        public readonly long EquipReLifeSteal;

        /// <summary>
        /// 抗闪避
        /// </summary>
        public readonly long EquipReEva;


        public const int __ID__ = -233858190;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ItemName:" + ItemName + ","
            + "HideType:" + Luban.StringUtil.CollectionToString(HideType) + ","
            + "HideShowPro:" + HideShowPro + ","
            + "SellResourcesType:" + Luban.StringUtil.CollectionToString(SellResourcesType) + ","
            + "SellResourcesValue:" + Luban.StringUtil.CollectionToString(SellResourcesValue) + ","
            + "EquipMinAct:" + EquipMinAct + ","
            + "EquipMaxAct:" + EquipMaxAct + ","
            + "EquipMinDef:" + EquipMinDef + ","
            + "EquipMaxDef:" + EquipMaxDef + ","
            + "EquipMinAdf:" + EquipMinAdf + ","
            + "EquipMaxAdf:" + EquipMaxAdf + ","
            + "EquipHp:" + EquipHp + ","
            + "EquipAtkSpeed:" + EquipAtkSpeed + ","
            + "EquipMoveSpeed:" + EquipMoveSpeed + ","
            + "EquipCri:" + EquipCri + ","
            + "EquipCombo:" + EquipCombo + ","
            + "EquipCounterattack:" + EquipCounterattack + ","
            + "EquipLifeSteal:" + EquipLifeSteal + ","
            + "EquipEva:" + EquipEva + ","
            + "EquipReCri:" + EquipReCri + ","
            + "EquipReCombo:" + EquipReCombo + ","
            + "EquipReCounterattack:" + EquipReCounterattack + ","
            + "EquipReLifeSteal:" + EquipReLifeSteal + ","
            + "EquipReEva:" + EquipReEva + ","
            + "}";
        }

        partial void PostInit();
    }
}
