
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 装备穿戴插槽
    /// </summary>
    public enum EquipSlotType
    {
        /// <summary>
        /// 头盔孔位
        /// </summary>
        Toukui = 1,

        /// <summary>
        /// 衣服孔位
        /// </summary>
        Yifu = 2,

        /// <summary>
        /// 裤子孔位
        /// </summary>
        Kuzi = 3,

        /// <summary>
        /// 鞋子孔位
        /// </summary>
        Xiezi = 4,

        /// <summary>
        /// 项链孔位
        /// </summary>
        Xianglian = 5,

        /// <summary>
        /// 1号武器孔位
        /// </summary>
        Wuqi_1 = 6,

        /// <summary>
        /// 2号武器孔位(危境有个英雄可以装2个武器)
        /// </summary>
        Wuqi_2 = 7,

    }
}
