
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class HeroConfig : BeanBase
    {
        public HeroConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            HeroName = _buf.ReadString();
            HeroType = _buf.ReadInt();
            HeroTag = _buf.ReadInt();
            HeroHeadIcon = _buf.ReadString();
            HeroModelID = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); HeroUpStarNeed = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); HeroUpStarNeed[__index0] = __e0;}}
            DamageType = _buf.ReadInt();
            AtkID = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); SkillID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); SkillID[__index0] = __e0;}}
            BaseHp = _buf.ReadInt();
            BaseAct = _buf.ReadInt();
            BaseDef = _buf.ReadInt();
            BaseAdf = _buf.ReadInt();
            BaseCri = _buf.ReadDouble();
            BaseReCri = _buf.ReadDouble();
            BaseEva = _buf.ReadDouble();
            BaseHit = _buf.ReadDouble();
            BaseHitLess = _buf.ReadDouble();
            BaseMoveSpeed = _buf.ReadDouble();
            BaseAtkSpeed = _buf.ReadDouble();
            AtkDistance = _buf.ReadDouble();
            LvHp = _buf.ReadInt();
            LvAct = _buf.ReadInt();
            LvDef = _buf.ReadInt();
            LvAdf = _buf.ReadInt();
            HeroDescription = _buf.ReadString();

            PostInit();
        }

        public static HeroConfig DeserializeHeroConfig(ByteBuf _buf)
        {
            return new HeroConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 英雄名称
        /// </summary>
        public readonly string HeroName;

        /// <summary>
        /// 英雄类型
        /// </summary>
        public readonly int HeroType;

        /// <summary>
        /// 英雄标签
        /// </summary>
        public readonly int HeroTag;

        /// <summary>
        /// 英雄头像
        /// </summary>
        public readonly string HeroHeadIcon;

        /// <summary>
        /// 英雄模型ID
        /// </summary>
        public readonly string HeroModelID;

        /// <summary>
        /// 英雄升星需要的魂石
        /// </summary>
        public readonly int[] HeroUpStarNeed;

        /// <summary>
        /// 伤害类型
        /// </summary>
        public readonly int DamageType;

        /// <summary>
        /// 普通攻击ID
        /// </summary>
        public readonly int AtkID;

        /// <summary>
        /// 英雄技能ID
        /// </summary>
        public readonly int[] SkillID;

        /// <summary>
        /// 血量
        /// </summary>
        public readonly int BaseHp;

        /// <summary>
        /// 攻击
        /// </summary>
        public readonly int BaseAct;

        /// <summary>
        /// 物防
        /// </summary>
        public readonly int BaseDef;

        /// <summary>
        /// 魔防
        /// </summary>
        public readonly int BaseAdf;

        /// <summary>
        /// 暴击
        /// </summary>
        public readonly double BaseCri;

        /// <summary>
        /// 抗暴
        /// </summary>
        public readonly double BaseReCri;

        /// <summary>
        /// 闪避
        /// </summary>
        public readonly double BaseEva;

        /// <summary>
        /// 命中
        /// </summary>
        public readonly double BaseHit;

        /// <summary>
        /// 伤害减免
        /// </summary>
        public readonly double BaseHitLess;

        /// <summary>
        /// 移动速度
        /// </summary>
        public readonly double BaseMoveSpeed;

        /// <summary>
        /// 攻击速度
        /// </summary>
        public readonly double BaseAtkSpeed;

        /// <summary>
        /// 攻击距离
        /// </summary>
        public readonly double AtkDistance;

        /// <summary>
        /// 等级成长血量
        /// </summary>
        public readonly int LvHp;

        /// <summary>
        /// 等级成长攻击
        /// </summary>
        public readonly int LvAct;

        /// <summary>
        /// 等级成长物防
        /// </summary>
        public readonly int LvDef;

        /// <summary>
        /// 等级成长魔防
        /// </summary>
        public readonly int LvAdf;

        /// <summary>
        /// 英雄简介
        /// </summary>
        public readonly string HeroDescription;


        public const int __ID__ = -563759108;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "HeroName:" + HeroName + ","
            + "HeroType:" + HeroType + ","
            + "HeroTag:" + HeroTag + ","
            + "HeroHeadIcon:" + HeroHeadIcon + ","
            + "HeroModelID:" + HeroModelID + ","
            + "HeroUpStarNeed:" + Luban.StringUtil.CollectionToString(HeroUpStarNeed) + ","
            + "DamageType:" + DamageType + ","
            + "AtkID:" + AtkID + ","
            + "SkillID:" + Luban.StringUtil.CollectionToString(SkillID) + ","
            + "BaseHp:" + BaseHp + ","
            + "BaseAct:" + BaseAct + ","
            + "BaseDef:" + BaseDef + ","
            + "BaseAdf:" + BaseAdf + ","
            + "BaseCri:" + BaseCri + ","
            + "BaseReCri:" + BaseReCri + ","
            + "BaseEva:" + BaseEva + ","
            + "BaseHit:" + BaseHit + ","
            + "BaseHitLess:" + BaseHitLess + ","
            + "BaseMoveSpeed:" + BaseMoveSpeed + ","
            + "BaseAtkSpeed:" + BaseAtkSpeed + ","
            + "AtkDistance:" + AtkDistance + ","
            + "LvHp:" + LvHp + ","
            + "LvAct:" + LvAct + ","
            + "LvDef:" + LvDef + ","
            + "LvAdf:" + LvAdf + ","
            + "HeroDescription:" + HeroDescription + ","
            + "}";
        }

        partial void PostInit();
    }
}
