
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 消耗品类型
    /// </summary>
    public enum ItemSubType
    {
        None = 0,

        /// <summary>
        /// 获得金币值
        /// </summary>
        GetGold = 1,

        /// <summary>
        /// 获得经验值
        /// </summary>
        GetExp = 2,

        /// <summary>
        /// 随机宝箱
        /// </summary>
        SuiJiBaoXian = 3,

        /// <summary>
        /// 自选宝箱
        /// </summary>
        ZiXuanBaoXian = 4,

        /// <summary>
        /// 使用后永久增加属性
        /// </summary>
        Type_5 = 5,

        /// <summary>
        /// 抽奖券
        /// </summary>
        Type_6 = 6,

        /// <summary>
        /// 副本入场券
        /// </summary>
        Type_7 = 7,

        /// <summary>
        /// 英雄经验
        /// </summary>
        HeroExp = 8,

        /// <summary>
        /// 英雄魂石
        /// </summary>
        HeroHunshi = 9,

        /// <summary>
        /// 英雄碎片
        /// </summary>
        Type_10 = 10,

        /// <summary>
        /// 头盔
        /// </summary>
        Toukui = 3001,

        /// <summary>
        /// 衣服
        /// </summary>
        Yifu = 3002,

        /// <summary>
        /// 裤子
        /// </summary>
        Kuzi = 3003,

        /// <summary>
        /// 鞋子
        /// </summary>
        Xiezi = 3004,

        /// <summary>
        /// 项链
        /// </summary>
        Xianglian = 3005,

        /// <summary>
        /// 武器
        /// </summary>
        Wuqi = 3006,

    }
}
