
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 消耗品类型
    /// </summary>
    public enum ItemConsumeType
    {
        /// <summary>
        /// 获得金币值
        /// </summary>
        GetGold = 1,

        /// <summary>
        /// 获得经验值
        /// </summary>
        GetExp = 2,

        /// <summary>
        /// 随机宝箱
        /// </summary>
        BaoXian = 3,

    }
}
