
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MonthSignInConfig : BeanBase
    {
        public MonthSignInConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            SignInType = _buf.ReadInt();
            RequiredDay = _buf.ReadInt();
            RewardItem = ExternalTypeUtil.NewRewardItem(global::ET.rewardItem.DeserializerewardItem(_buf));

            PostInit();
        }

        public static MonthSignInConfig DeserializeMonthSignInConfig(ByteBuf _buf)
        {
            return new MonthSignInConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 签到类型
        /// </summary>
        public readonly int SignInType;

        /// <summary>
        /// 签到天数
        /// </summary>
        public readonly int RequiredDay;

        /// <summary>
        /// 奖励道具
        /// </summary>
        public readonly ET.RewardItem RewardItem;


        public const int __ID__ = 1299871780;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "SignInType:" + SignInType + ","
            + "RequiredDay:" + RequiredDay + ","
            + "RewardItem:" + RewardItem + ","
            + "}";
        }

        partial void PostInit();
    }
}
