
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class NPCConfig : BeanBase
    {
        public NPCConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Model = _buf.ReadString();
            Position = ExternalTypeUtil.NewVector2(global::ET.vector2.Deserializevector2(_buf));
            OpenUI = _buf.ReadString();
            DialogueText = _buf.ReadString();

            PostInit();
        }

        public static NPCConfig DeserializeNPCConfig(ByteBuf _buf)
        {
            return new NPCConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 名字
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 模型
        /// </summary>
        public readonly string Model;

        /// <summary>
        /// 位置
        /// </summary>
        public readonly System.Numerics.Vector2 Position;

        /// <summary>
        /// UI
        /// </summary>
        public readonly string OpenUI;

        /// <summary>
        /// 对话内容
        /// </summary>
        public readonly string DialogueText;


        public const int __ID__ = -199374493;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "Model:" + Model + ","
            + "Position:" + Position + ","
            + "OpenUI:" + OpenUI + ","
            + "DialogueText:" + DialogueText + ","
            + "}";
        }

        partial void PostInit();
    }
}
