
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class RechargePointsRewardConfigCategory : Singleton<RechargePointsRewardConfigCategory>, IConfig
    {
        private readonly Dictionary<int, RechargePointsRewardConfig> _dataMap;
        private readonly List<RechargePointsRewardConfig> _dataList;

        public RechargePointsRewardConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, RechargePointsRewardConfig>();
            _dataList = new List<RechargePointsRewardConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                RechargePointsRewardConfig _v;
                _v = global::ET.RechargePointsRewardConfig.DeserializeRechargePointsRewardConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, RechargePointsRewardConfig> DataMap => _dataMap;
        public List<RechargePointsRewardConfig> DataList => _dataList;

        public RechargePointsRewardConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public RechargePointsRewardConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
