
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    public partial struct rewardItem
    {
        public rewardItem(ByteBuf _buf)
        {
            ItemId = _buf.ReadInt();
            ItemNum = _buf.ReadInt();

            PostInit();
        }

        public static rewardItem DeserializerewardItem(ByteBuf _buf)
        {
            return new rewardItem(_buf);
        }

        public readonly int ItemId;

        public readonly int ItemNum;



        public  void ResolveRef()
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "ItemId:" + ItemId + ","
            + "ItemNum:" + ItemNum + ","
            + "}";
        }

        partial void PostInit();
    }
}
