
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 技能类型
    /// </summary>
    public enum SkillType
    {
        None = 0,

        /// <summary>
        /// 主动技能
        /// </summary>
        Active = 1,

        /// <summary>
        /// 被动技能
        /// </summary>
        Passive = 2,

    }
}
