
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 被动技能触发类型
    /// </summary>
    public enum SkillPassiveType
    {
        /// <summary>
        /// 无视
        /// </summary>
        None = 0,

        /// <summary>
        /// 受到伤害触发概率
        /// </summary>
        OnDamagedByChance = 1,

        /// <summary>
        /// 普通攻击触发概率
        /// </summary>
        OnNormalAttackByChance = 2,

        /// <summary>
        /// 血量低于多少百分比触发
        /// </summary>
        OnSelfHpBelowPercent = 3,

        /// <summary>
        /// 开始战斗就触发
        /// </summary>
        OnBattleStart = 4,

        /// <summary>
        /// 队友血量低于多少百分比触发
        /// </summary>
        OnTeamHpBelowPercent = 5,

    }
}
