
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class StoreItemConfigCategory : Singleton<StoreItemConfigCategory>, IConfig
    {
        private readonly Dictionary<int, StoreItemConfig> _dataMap;
        private readonly List<StoreItemConfig> _dataList;

        public StoreItemConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, StoreItemConfig>();
            _dataList = new List<StoreItemConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                StoreItemConfig _v;
                _v = global::ET.StoreItemConfig.DeserializeStoreItemConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, StoreItemConfig> DataMap => _dataMap;
        public List<StoreItemConfig> DataList => _dataList;

        public StoreItemConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public StoreItemConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
