
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 伤害类型
    /// </summary>
    public enum DamageType
    {
        None = 0,

        /// <summary>
        /// 物理
        /// </summary>
        Physical = 1,

        /// <summary>
        /// 魔法
        /// </summary>
        Magical = 2,

        /// <summary>
        /// 暴击
        /// </summary>
        Critical = 3,

        /// <summary>
        /// 闪避
        /// </summary>
        Dodge = 4,

        /// <summary>
        /// 恢复
        /// </summary>
        Recover = 5,

        /// <summary>
        /// 免疫
        /// </summary>
        Immune = 6,

    }
}
