
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ExpConfig : BeanBase
    {
        public ExpConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            PlayerUpExp = _buf.ReadInt();
            HeroUpExp = _buf.ReadInt();

            PostInit();
        }

        public static ExpConfig DeserializeExpConfig(ByteBuf _buf)
        {
            return new ExpConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 玩家升级经验
        /// </summary>
        public readonly int PlayerUpExp;

        /// <summary>
        /// 英雄升级经验
        /// </summary>
        public readonly int HeroUpExp;


        public const int __ID__ = 1163743135;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "PlayerUpExp:" + PlayerUpExp + ","
            + "HeroUpExp:" + HeroUpExp + ","
            + "}";
        }

        partial void PostInit();
    }
}
