
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class GlobalValueConfig : BeanBase
    {
        public GlobalValueConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Des = _buf.ReadString();
            Value = _buf.ReadString();

            PostInit();
        }

        public static GlobalValueConfig DeserializeGlobalValueConfig(ByteBuf _buf)
        {
            return new GlobalValueConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 测试说明
        /// </summary>
        public readonly string Des;

        /// <summary>
        /// 值
        /// </summary>
        public readonly string Value;


        public const int __ID__ = -2026784688;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Des:" + Des + ","
            + "Value:" + Value + ","
            + "}";
        }

        partial void PostInit();
    }
}
