
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class HeroConfig : BeanBase
    {
        public HeroConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            HeroName = _buf.ReadString();
            HeroType = _buf.ReadInt();
            HeroHeadIcon = _buf.ReadString();
            HeroModelID = _buf.ReadInt();
            HeroQuality = _buf.ReadInt();
            AtkDistance = _buf.ReadInt();
            AtkID = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); SkillID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); SkillID[__index0] = __e0;}}
            Act = _buf.ReadInt();
            Def = _buf.ReadInt();
            Hp = _buf.ReadInt();
            AtkSpeed = _buf.ReadDouble();
            MoveSpeed = _buf.ReadDouble();
            Cri = _buf.ReadDouble();
            Combo = _buf.ReadDouble();
            Counterattack = _buf.ReadDouble();
            LifeSteal = _buf.ReadDouble();
            Eva = _buf.ReadDouble();
            ReCri = _buf.ReadDouble();
            ReCombo = _buf.ReadDouble();
            ReCounterattack = _buf.ReadDouble();
            ReLifeSteal = _buf.ReadDouble();
            ReEva = _buf.ReadDouble();
            HeroDescription = _buf.ReadString();

            PostInit();
        }

        public static HeroConfig DeserializeHeroConfig(ByteBuf _buf)
        {
            return new HeroConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 英雄名称
        /// </summary>
        public readonly string HeroName;

        /// <summary>
        /// 英雄类型
        /// </summary>
        public readonly int HeroType;

        /// <summary>
        /// 英雄头像
        /// </summary>
        public readonly string HeroHeadIcon;

        /// <summary>
        /// 英雄模型ID
        /// </summary>
        public readonly int HeroModelID;

        /// <summary>
        /// 英雄品质
        /// </summary>
        public readonly int HeroQuality;

        /// <summary>
        /// 攻击距离
        /// </summary>
        public readonly int AtkDistance;

        /// <summary>
        /// 普通攻击ID
        /// </summary>
        public readonly int AtkID;

        /// <summary>
        /// 英雄技能ID
        /// </summary>
        public readonly int[] SkillID;

        /// <summary>
        /// 初始攻击
        /// </summary>
        public readonly int Act;

        /// <summary>
        /// 初始防御
        /// </summary>
        public readonly int Def;

        /// <summary>
        /// 初始生命
        /// </summary>
        public readonly int Hp;

        /// <summary>
        /// 初始攻速
        /// </summary>
        public readonly double AtkSpeed;

        /// <summary>
        /// 初始移速
        /// </summary>
        public readonly double MoveSpeed;

        /// <summary>
        /// 初始暴击
        /// </summary>
        public readonly double Cri;

        /// <summary>
        /// 初始连击
        /// </summary>
        public readonly double Combo;

        /// <summary>
        /// 初始反击
        /// </summary>
        public readonly double Counterattack;

        /// <summary>
        /// 初始吸血
        /// </summary>
        public readonly double LifeSteal;

        /// <summary>
        /// 初始闪避
        /// </summary>
        public readonly double Eva;

        /// <summary>
        /// 初始抗暴击
        /// </summary>
        public readonly double ReCri;

        /// <summary>
        /// 初始抗连击
        /// </summary>
        public readonly double ReCombo;

        /// <summary>
        /// 初始抗反击
        /// </summary>
        public readonly double ReCounterattack;

        /// <summary>
        /// 初始抗吸血
        /// </summary>
        public readonly double ReLifeSteal;

        /// <summary>
        /// 初始抗闪避
        /// </summary>
        public readonly double ReEva;

        /// <summary>
        /// 英雄简介
        /// </summary>
        public readonly string HeroDescription;


        public const int __ID__ = -563759108;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "HeroName:" + HeroName + ","
            + "HeroType:" + HeroType + ","
            + "HeroHeadIcon:" + HeroHeadIcon + ","
            + "HeroModelID:" + HeroModelID + ","
            + "HeroQuality:" + HeroQuality + ","
            + "AtkDistance:" + AtkDistance + ","
            + "AtkID:" + AtkID + ","
            + "SkillID:" + Luban.StringUtil.CollectionToString(SkillID) + ","
            + "Act:" + Act + ","
            + "Def:" + Def + ","
            + "Hp:" + Hp + ","
            + "AtkSpeed:" + AtkSpeed + ","
            + "MoveSpeed:" + MoveSpeed + ","
            + "Cri:" + Cri + ","
            + "Combo:" + Combo + ","
            + "Counterattack:" + Counterattack + ","
            + "LifeSteal:" + LifeSteal + ","
            + "Eva:" + Eva + ","
            + "ReCri:" + ReCri + ","
            + "ReCombo:" + ReCombo + ","
            + "ReCounterattack:" + ReCounterattack + ","
            + "ReLifeSteal:" + ReLifeSteal + ","
            + "ReEva:" + ReEva + ","
            + "HeroDescription:" + HeroDescription + ","
            + "}";
        }

        partial void PostInit();
    }
}
