
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 道具类型
    /// </summary>
    public enum ItemType
    {
        None = 0,

        /// <summary>
        /// 消耗
        /// </summary>
        Consume = 1,

        /// <summary>
        /// 材料
        /// </summary>
        Material = 2,

        /// <summary>
        /// 装备
        /// </summary>
        Equipment = 3,

    }
}
