
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 装备类型
    /// </summary>
    public enum ItemEquipmentType
    {
        None = 0,

        /// <summary>
        /// 头盔
        /// </summary>
        Toukui = 1,

        /// <summary>
        /// 衣服
        /// </summary>
        Yifu = 2,

        /// <summary>
        /// 裤子
        /// </summary>
        Kuzi = 3,

        /// <summary>
        /// 鞋子
        /// </summary>
        Xiezi = 4,

        /// <summary>
        /// 项链
        /// </summary>
        Xianglian = 5,

        /// <summary>
        /// 武器
        /// </summary>
        Wuqi = 6,

    }
}
