
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class LevelConfigCategory : Singleton<LevelConfigCategory>, IConfig
    {
        private readonly Dictionary<int, LevelConfig> _dataMap;
        private readonly List<LevelConfig> _dataList;

        public LevelConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, LevelConfig>();
            _dataList = new List<LevelConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                LevelConfig _v;
                _v = global::ET.LevelConfig.DeserializeLevelConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, LevelConfig> DataMap => _dataMap;
        public List<LevelConfig> DataList => _dataList;

        public LevelConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public LevelConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
