
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class LevelConfig : BeanBase
    {
        public LevelConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            LevelName = _buf.ReadString();
            SceneName = _buf.ReadString();
            {int __n0 = _buf.ReadSize(); WaveIds = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); WaveIds[__index0] = __e0;}}
            RewardExp = _buf.ReadInt();

            PostInit();
        }

        public static LevelConfig DeserializeLevelConfig(ByteBuf _buf)
        {
            return new LevelConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 关卡名称
        /// </summary>
        public readonly string LevelName;

        /// <summary>
        /// 地图名称
        /// </summary>
        public readonly string SceneName;

        /// <summary>
        /// 波
        /// </summary>
        public readonly int[] WaveIds;

        /// <summary>
        /// 通关获得经验
        /// </summary>
        public readonly int RewardExp;


        public const int __ID__ = -1308229690;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "LevelName:" + LevelName + ","
            + "SceneName:" + SceneName + ","
            + "WaveIds:" + Luban.StringUtil.CollectionToString(WaveIds) + ","
            + "RewardExp:" + RewardExp + ","
            + "}";
        }

        partial void PostInit();
    }
}
