
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MonsterConfig : BeanBase
    {
        public MonsterConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            MonsterName = _buf.ReadString();
            MonsterHeadIcon = _buf.ReadString();
            MonsterType = _buf.ReadInt();
            MonsterModelID = _buf.ReadString();
            ChallengeTime = _buf.ReadInt();
            ActSkillID = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); SkillID = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); SkillID[__index0] = __e0;}}
            Lv = _buf.ReadInt();
            MoveSpeed = _buf.ReadLong();
            ActDistance = _buf.ReadLong();
            AtkSpeed = _buf.ReadLong();
            Hp = _buf.ReadInt();
            Act = _buf.ReadInt();
            Def = _buf.ReadInt();
            Adf = _buf.ReadInt();
            Cri = _buf.ReadLong();
            ReCri = _buf.ReadLong();
            Eva = _buf.ReadLong();
            Hit = _buf.ReadLong();
            HitLess = _buf.ReadLong();
            MonsterDescription = _buf.ReadString();
            AI = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); DropId = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); DropId[__index0] = __e0;}}

            PostInit();
        }

        public static MonsterConfig DeserializeMonsterConfig(ByteBuf _buf)
        {
            return new MonsterConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 怪物名称
        /// </summary>
        public readonly string MonsterName;

        /// <summary>
        /// 怪物头像
        /// </summary>
        public readonly string MonsterHeadIcon;

        /// <summary>
        /// 怪物类型
        /// </summary>
        public readonly int MonsterType;

        /// <summary>
        /// 怪物模型ID
        /// </summary>
        public readonly string MonsterModelID;

        /// <summary>
        /// 怪物挑战时间[秒]
        /// </summary>
        public readonly int ChallengeTime;

        /// <summary>
        /// 普通攻击ID
        /// </summary>
        public readonly int ActSkillID;

        /// <summary>
        /// 怪物技能ID
        /// </summary>
        public readonly int[] SkillID;

        /// <summary>
        /// 怪物等级
        /// </summary>
        public readonly int Lv;

        /// <summary>
        /// 移动速度
        /// </summary>
        public readonly long MoveSpeed;

        /// <summary>
        /// 攻击距离
        /// </summary>
        public readonly long ActDistance;

        /// <summary>
        /// 攻击速度
        /// </summary>
        public readonly long AtkSpeed;

        /// <summary>
        /// 怪物生命
        /// </summary>
        public readonly int Hp;

        /// <summary>
        /// 攻击
        /// </summary>
        public readonly int Act;

        /// <summary>
        /// 物理防御
        /// </summary>
        public readonly int Def;

        /// <summary>
        /// 魔法防御
        /// </summary>
        public readonly int Adf;

        /// <summary>
        /// 暴击概率
        /// </summary>
        public readonly long Cri;

        /// <summary>
        /// 抗爆概率
        /// </summary>
        public readonly long ReCri;

        /// <summary>
        /// 闪避概率
        /// </summary>
        public readonly long Eva;

        /// <summary>
        /// 命中概率
        /// </summary>
        public readonly long Hit;

        /// <summary>
        /// 伤害减免
        /// </summary>
        public readonly long HitLess;

        /// <summary>
        /// 怪物简介
        /// </summary>
        public readonly string MonsterDescription;

        /// <summary>
        /// AI
        /// </summary>
        public readonly int AI;

        /// <summary>
        /// 掉落物
        /// </summary>
        public readonly int[] DropId;


        public const int __ID__ = -55174244;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "MonsterName:" + MonsterName + ","
            + "MonsterHeadIcon:" + MonsterHeadIcon + ","
            + "MonsterType:" + MonsterType + ","
            + "MonsterModelID:" + MonsterModelID + ","
            + "ChallengeTime:" + ChallengeTime + ","
            + "ActSkillID:" + ActSkillID + ","
            + "SkillID:" + Luban.StringUtil.CollectionToString(SkillID) + ","
            + "Lv:" + Lv + ","
            + "MoveSpeed:" + MoveSpeed + ","
            + "ActDistance:" + ActDistance + ","
            + "AtkSpeed:" + AtkSpeed + ","
            + "Hp:" + Hp + ","
            + "Act:" + Act + ","
            + "Def:" + Def + ","
            + "Adf:" + Adf + ","
            + "Cri:" + Cri + ","
            + "ReCri:" + ReCri + ","
            + "Eva:" + Eva + ","
            + "Hit:" + Hit + ","
            + "HitLess:" + HitLess + ","
            + "MonsterDescription:" + MonsterDescription + ","
            + "AI:" + AI + ","
            + "DropId:" + Luban.StringUtil.CollectionToString(DropId) + ","
            + "}";
        }

        partial void PostInit();
    }
}
