
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class MonsterBatchConfigCategory : Singleton<MonsterBatchConfigCategory>, IConfig
    {
        private readonly Dictionary<int, MonsterBatchConfig> _dataMap;
        private readonly List<MonsterBatchConfig> _dataList;

        public MonsterBatchConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, MonsterBatchConfig>();
            _dataList = new List<MonsterBatchConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                MonsterBatchConfig _v;
                _v = global::ET.MonsterBatchConfig.DeserializeMonsterBatchConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, MonsterBatchConfig> DataMap => _dataMap;
        public List<MonsterBatchConfig> DataList => _dataList;

        public MonsterBatchConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public MonsterBatchConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
