
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class RechargeConfigCategory : Singleton<RechargeConfigCategory>, IConfig
    {
        private readonly Dictionary<int, RechargeConfig> _dataMap;
        private readonly List<RechargeConfig> _dataList;

        public RechargeConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, RechargeConfig>();
            _dataList = new List<RechargeConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                RechargeConfig _v;
                _v = global::ET.RechargeConfig.DeserializeRechargeConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, RechargeConfig> DataMap => _dataMap;
        public List<RechargeConfig> DataList => _dataList;

        public RechargeConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public RechargeConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
