
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 技能目标类型
    /// </summary>
    public enum SkillTargetType
    {
        /// <summary>
        /// 立即释放,自身中心点范围
        /// </summary>
        SelfPosition = 0,

        /// <summary>
        /// 立即释放,目标中心点范围
        /// </summary>
        TargetPositon = 1,

        /// <summary>
        /// 单体指定目标
        /// </summary>
        TargetOnly = 2,

        /// <summary>
        /// 单体指定自己
        /// </summary>
        SelfOnly = 3,

        /// <summary>
        /// 单体技能多个目标
        /// </summary>
        MulTarget = 4,

        /// <summary>
        /// 全体队友
        /// </summary>
        AllTeam = 5,

        /// <summary>
        /// 全体敌人
        /// </summary>
        AllEnemy = 6,

    }
}
