
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 技能攻击类型
    /// </summary>
    public enum SkillActType
    {
        /// <summary>
        /// 普通攻击
        /// </summary>
        Normal = 0,

        /// <summary>
        /// 技能攻击
        /// </summary>
        Skill = 1,

    }
}
