
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 状态
    /// </summary>
    [System.Flags]
    public enum StateType
    {
        None = 0,

        /// <summary>
        /// 无敌
        /// </summary>
        AllDamageImmune = 1,

        /// <summary>
        /// 免疫物理攻击
        /// </summary>
        PhysicalImmune = 2,

    }
}
