
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    /// <summary>
    /// 任务目标类型
    /// </summary>
    public enum TaskTargetType
    {
        /// <summary>
        /// 等级达到指定等级
        /// </summary>
        PlayerLv = 1,

        /// <summary>
        /// 击杀任意怪物
        /// </summary>
        KillMonster = 2,

        /// <summary>
        /// 击杀任意BOSS
        /// </summary>
        KillBOSS = 3,

        /// <summary>
        /// 杀怪
        /// </summary>
        KillMonsterId = 4,

        /// <summary>
        /// 通关指定关卡
        /// </summary>
        PassLeveld = 5,

        /// <summary>
        /// 战力达到多少
        /// </summary>
        CombatPower = 6,

    }
}
