
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class TaskConfig : BeanBase
    {
        public TaskConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            TaskName = _buf.ReadString();
            TaskType = _buf.ReadInt();
            TriggerType = _buf.ReadInt();
            TriggerValue = _buf.ReadInt();
            TaskExp = _buf.ReadInt();
            TaskGold = _buf.ReadInt();
            ItemID = _buf.ReadString();
            TargetType = _buf.ReadInt();
            {int __n0 = _buf.ReadSize(); Target = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); Target[__index0] = __e0;}}
            {int __n0 = _buf.ReadSize(); TargetValue = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); TargetValue[__index0] = __e0;}}
            ItemNum = _buf.ReadString();
            TaskDes = _buf.ReadString();

            PostInit();
        }

        public static TaskConfig DeserializeTaskConfig(ByteBuf _buf)
        {
            return new TaskConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 任务名称
        /// </summary>
        public readonly string TaskName;

        /// <summary>
        /// 任务类型
        /// </summary>
        public readonly int TaskType;

        /// <summary>
        /// 触发类型
        /// </summary>
        public readonly int TriggerType;

        /// <summary>
        /// 触发值
        /// </summary>
        public readonly int TriggerValue;

        /// <summary>
        /// 任务经验
        /// </summary>
        public readonly int TaskExp;

        /// <summary>
        /// 任务金币
        /// </summary>
        public readonly int TaskGold;

        /// <summary>
        /// 奖励道具ID
        /// </summary>
        public readonly string ItemID;

        /// <summary>
        /// 目标类型
        /// </summary>
        public readonly int TargetType;

        /// <summary>
        /// 目标ID
        /// </summary>
        public readonly int[] Target;

        /// <summary>
        /// 目标值
        /// </summary>
        public readonly int[] TargetValue;

        /// <summary>
        /// 奖励道具数量
        /// </summary>
        public readonly string ItemNum;

        /// <summary>
        /// 任务描述
        /// </summary>
        public readonly string TaskDes;


        public const int __ID__ = -1794275001;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
            
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "TaskName:" + TaskName + ","
            + "TaskType:" + TaskType + ","
            + "TriggerType:" + TriggerType + ","
            + "TriggerValue:" + TriggerValue + ","
            + "TaskExp:" + TaskExp + ","
            + "TaskGold:" + TaskGold + ","
            + "ItemID:" + ItemID + ","
            + "TargetType:" + TargetType + ","
            + "Target:" + Luban.StringUtil.CollectionToString(Target) + ","
            + "TargetValue:" + Luban.StringUtil.CollectionToString(TargetValue) + ","
            + "ItemNum:" + ItemNum + ","
            + "TaskDes:" + TaskDes + ","
            + "}";
        }

        partial void PostInit();
    }
}
