
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class UnlockSkillInfo : BeanBase
    {
        public UnlockSkillInfo(ByteBuf _buf)
        {
            UnlockStar = _buf.ReadInt();
            SkillConfigId = _buf.ReadInt();

            PostInit();
        }

        public static UnlockSkillInfo DeserializeUnlockSkillInfo(ByteBuf _buf)
        {
            return new UnlockSkillInfo(_buf);
        }

        /// <summary>
        /// 解锁星级
        /// </summary>
        public readonly int UnlockStar;

        /// <summary>
        /// 技能配置Id
        /// </summary>
        public readonly int SkillConfigId;


        public const int __ID__ = 1974728603;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "UnlockStar:" + UnlockStar + ","
            + "SkillConfigId:" + SkillConfigId + ","
            + "}";
        }

        partial void PostInit();
    }
}
