
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class WaveConfig : BeanBase
    {
        public WaveConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            HaveBoss = _buf.ReadBool();
            PlayerSpawnPosition = ExternalTypeUtil.NewVector2(global::ET.vector2.Deserializevector2(_buf));
            {int __n0 = _buf.ReadSize(); MonsterSpawnInfos = new monsterSpawnInfo[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { monsterSpawnInfo __e0;__e0 = global::ET.monsterSpawnInfo.DeserializemonsterSpawnInfo(_buf); MonsterSpawnInfos[__index0] = __e0;}}

            PostInit();
        }

        public static WaveConfig DeserializeWaveConfig(ByteBuf _buf)
        {
            return new WaveConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 关卡名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 有Boss
        /// </summary>
        public readonly bool HaveBoss;

        /// <summary>
        /// 玩家出生点
        /// </summary>
        public readonly System.Numerics.Vector2 PlayerSpawnPosition;

        /// <summary>
        /// 怪物生成
        /// </summary>
        public readonly monsterSpawnInfo[] MonsterSpawnInfos;


        public const int __ID__ = 1814560699;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            foreach (var _e in MonsterSpawnInfos) { _e?.ResolveRef(); }
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "HaveBoss:" + HaveBoss + ","
            + "PlayerSpawnPosition:" + PlayerSpawnPosition + ","
            + "MonsterSpawnInfos:" + Luban.StringUtil.CollectionToString(MonsterSpawnInfos) + ","
            + "}";
        }

        partial void PostInit();
    }
}
