syntax = "proto3";
package ET;

message HttpGetRouterResponse
{
	repeated string Realms = 1;
	repeated string Routers = 2;
}

message RouterSync
{
	uint32 ConnectId = 1;
	string Address = 2;
}

//ResponseType M2C_TestResponse
message C2M_TestRequest // ILocationRequest
{
	int32 RpcId = 1;
	string request = 2;
}

message M2C_TestResponse // IResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	string response = 4;
}

//ResponseType G2C_EnterGame
message C2G_EnterGame // ISessionRequest
{
	int32 RpcId = 1;
	int64 UnitId = 2;
	int64 AccountId = 3;
	int32 ReLink = 4;
}

message G2C_EnterGame // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	// 自己unitId
	int64 MyId = 4;
}

message MoveInfo
{
	repeated Unity.Mathematics.float3 Points = 1;
	Unity.Mathematics.quaternion Rotation = 2;
	int32 TurnSpeed = 3;
}

message UnitInfo
{
	int64 UnitId = 1;
	int32 ConfigId = 2;
	int32 Type = 3;
	Unity.Mathematics.float3 Position = 4;
	Unity.Mathematics.float3 Forward = 5;
	map<int32, int64> KV = 6;
	MoveInfo MoveInfo = 7;

	string UnitName = 21;
	string MasterName = 22;
}

message M2C_CreateUnits // IMessage
{
	repeated UnitInfo Units = 1;
	int32 UpdateAll = 8;
}

message M2C_CreateMyUnit // IMessage
{
	UnitInfo Unit = 1;
}

message M2C_StartSceneChange // IMessage
{
	int64 SceneInstanceId = 1;

	int32 SceneType = 2;
	int32 SceneId = 3;
	int32 Difficulty = 4;
	string ParamInfo = 5;
}

message M2C_RemoveUnits // IMessage
{
	repeated int64 Units = 1;
}

message C2M_PathfindingRequest // ILocationMessage
{
	int32 RpcId = 1;
	Unity.Mathematics.float3 Position = 2;
}

///客户端寻路
message C2M_PathfindingResult // ILocationMessage
{
	int32 RpcId = 1;
  
	int32 SpeedRate = 3;
	int64 ServerTime = 4;   //服务器时间戳
	repeated	Unity.Mathematics.float3 Position = 5;
	Unity.Mathematics.float3 Current = 6;   //当前位置
	int32 Frame = 7;                        //当前帧
}

message C2M_Stop // ILocationMessage
{
	int32 RpcId = 1;
	bool YaoGan = 4;
}

message M2C_Stop // IMessage
{
	int32 Error = 1;
	int64 Id = 2;
	Unity.Mathematics.float3 Position = 3;
	Unity.Mathematics.quaternion Rotation = 4;
}

message C2M_StopResult // ILocationMessage
{
	int32 RpcId = 1;
	Unity.Mathematics.float3 Position = 3;
}

message M2C_StopResult // IMessage
{
	int32 Error = 1;
	int64 Id = 2;
	Unity.Mathematics.float3 Position = 3;
	Unity.Mathematics.quaternion Rotation = 4;
}

message M2C_PathfindingResult // IMessage
{
	int64 Id = 1;
	Unity.Mathematics.float3 Position = 2;
	repeated Unity.Mathematics.float3 Points = 3;
	bool YaoGan = 4;
	int32 SpeedRate = 5;
}

//ResponseType G2C_Ping
message C2G_Ping // ISessionRequest
{
	int32 RpcId = 1;
}

message G2C_Ping // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 Time = 4;
}

//ResponseType R2C_Ping
message C2R_Ping // ISessionRequest
{
	int32 RpcId = 1;
}

message R2C_Ping // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 Time = 4;
}


message G2C_Test // ISessionMessage
{
}

//ResponseType M2C_Reload
message C2M_Reload // ISessionRequest
{
	int32 RpcId = 1;
	string Account = 2;
	string Password = 3;
}

message M2C_Reload // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

message ServerItem
{
	int32 ServerId = 1;
	string ServerIp = 2;
	string ServerName = 3;
	int64 ServerOpenTime = 4;
	int32 Show = 5;
	int32 New = 6;
	repeated int32 PlatformList = 7;   //不配置或者-1全部显示
	repeated int64 OldServerIds = 8;      //
}

//ResponseType R2C_DeleteAccountResponse
message C2R_DeleteAccountRequest // ISessionRequest
{
	int32 RpcId = 90;
	string Account = 1;
	string Password = 2;
}

message R2C_DeleteAccountResponse // ISessionResponse
{
	int32 RpcId = 90;
	int32 Error = 91;
	string Message = 92;
}


//ResponseType R2C_ServerList
message C2R_ServerList // ISessionRequest
{
	int32 RpcId = 1;
	int32 VersionMode = 2;
}

message R2C_ServerList // ISessionResponse
{
	int32 RpcId = 1;
	string Message = 2;
	int32 Error = 3;
	
	repeated ServerItem ServerItems = 4;		//服务器列表
	string NoticeVersion = 5;
	string NoticeText = 6;
}

//ResponseType R2C_LoginAccount
message C2R_LoginAccount // ISessionRequest
{
	int32 RpcId = 1;
	string  Account = 2;  // 帐号
	string  Password = 3;  // 密码
	string  Token = 4;  
	string  ThirdLogin = 5;
	int32 Relink = 6;
	int32 age_type = 7;
	int32  ServerId = 8;
	bool CheckRealName = 9;
}

message R2C_LoginAccount // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	string Address = 4;
	int64 GateId = 6;
	string Token = 7;
	int64 AccountId = 8;
	int32 QueueNumber = 9;
	string QueueAddres = 10;
	PlayerInfo PlayerInfo = 11;
	repeated CreateRoleInfo RoleLists = 12;
}

//ResponseType R2C_RealNameResponse
message C2R_RealNameRequest // ISessionRequest
{
	int32 RpcId = 90;
	string Name = 1;		//姓名
	string IdCardNO = 2;		//身份证号码
	int32 AiType = 3;			//1认证 2查询 3上报
	int64 AccountId	 = 4;	// 帐号Id
}

message R2C_RealNameResponse // ISessionResponse
{
	int32 RpcId = 90;
	int32 Error = 91;
	string Message = 92;
	int32 ErrorCode = 1;		//实名认证返回
	PlayerInfo PlayerInfo = 11;
}

//ResponseType M2C_RealNameResponse
message C2M_RealNameRequest // ILocationRequest
{
	int32 RpcId = 90;
	string Name = 1;		//姓名
	string IdCardNO = 2;		//身份证号码
	int32 AiType = 3;			//1认证 2查询 3上报
	int64 AccountId	 = 4;	// 帐号Id
}

message M2C_RealNameResponse // ILocationResponse
{
	int32 RpcId = 90;
	int32 Error = 91;
	string Message = 92;
	int32 ErrorCode = 1;		//实名认证返回
	PlayerInfo PlayerInfo = 11;
}

message RechargeInfo
{
	int32 Amount = 1;
	int64 Time = 2;
	int64 UnitId = 3;
	string OrderInfo = 4;
	int32 PhysicsZone = 5;
}

message PlayerInfo
{
	int32 RealName = 1;
	string Name = 2;
	string IdCardNo = 3;
	int32 RealNameReward = 4;
	repeated RechargeInfo RechargeInfos = 5;
	repeated KeyValuePair DeleteUserList = 6;
	repeated int32 BuChangZone = 7;
	string PhoneNumber = 8;
	repeated int64 ShareTimes = 9;
}

message CreateRoleInfo
{
	int64 UnitId = 1;
	int PlayerLv = 2;
	int PlayerOcc = 3;
	string PlayerName = 4;
	int32 RobotId = 5;
	int32 ServerId = 6;
	int32 State = 7;
}

//ResponseType G2C_LoginGameGate
message C2G_LoginGameGate // ISessionRequest
{
	int32 RpcId = 1;
	int64 Key = 2;  
	int64 GateId = 3;
	string  AccountName = 4;
	int64 RoleId = 5;
}

message G2C_LoginGameGate // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int64 PlayerId = 4;
}

//ResponseType R2C_CreateRoleData
message C2R_CreateRoleData // ISessionRequest
{
	int32 RpcId = 90;
	int32 CreateOcc = 2;
	string CreateName = 3;
	int64 AccountId = 4;
	int32 ServerId = 5;
}

message R2C_CreateRoleData // ISessionResponse
{
	int32 RpcId = 90;
	int32 Error = 91;
	string Message = 92;
	CreateRoleInfo createRoleInfo = 1;
}

//ResponseType R2C_DeleteRoleData
message C2R_DeleteRoleData // ISessionRequest
{
	int32 RpcId = 90;
	int64 AccountId = 1;
	int64 UserId = 2;
}

message R2C_DeleteRoleData // ISessionResponse
{
	int32 RpcId = 90;
	int32 Error = 91;
	string Message = 92;
}

//ResponseType Q2C_EnterQueue
message C2Q_EnterQueue // ISessionRequest
{
	int32 RpcId = 90;
	string Token = 1;
	string Account = 2;
	int64 AccountId = 3;
}

message Q2C_EnterQueue // ISessionResponse
{
	int32 RpcId = 90;
	int32 Error = 91;
	string Message = 92;
}

//ResponseType R2C_GetRealmKey
message C2R_GetRealmKey // ISessionRequest
{
	int32 RpcId = 1;
	string Token = 2;
	string Account = 3;
	int32 ServerId = 4;
}

message R2C_GetRealmKey // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	string Address = 4;
	int64 Key = 5;
	int64 GateId = 6;
}

message G2C_TestHotfixMessage // ISessionMessage
{
	string Info = 1;
}

//ResponseType M2C_TestRobotCase
message C2M_TestRobotCase // ILocationRequest
{
	int32 RpcId = 1;
	int32 N = 2;
}

message M2C_TestRobotCase // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	int32 N = 4;
}

message C2M_TestRobotCase2 // ILocationMessage
{
	int32 RpcId = 1;
	int32 N = 2;
}

message M2C_TestRobotCase2 // ILocationMessage
{
	int32 RpcId = 1;
	int32 N = 2;
}

//ResponseType M2C_TransferMap
message C2M_TransferMap // ILocationRequest
{
	int32 RpcId = 1;

	int32 SceneId = 2;
	int32 SceneType = 3;
	int32 Difficulty = 5;
	string paramInfo = 6;
}

message M2C_TransferMap // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

//ResponseType G2C_Benchmark
message C2G_Benchmark // ISessionRequest
{
	int32 RpcId = 1;
}

message G2C_Benchmark // ISessionResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

message ServerInfo
{
	int32 WorldLv = 1;
	int64 ExChangeGold = 2;
	int32 TianQi = 5;
	bool ShouLieOpen = 6;
	int32 ChouKaDropId = 7;   //每天随机
}

message A2C_Disconnect	//IMessage
{
	int32 Error = 1;
}

message G2C_SecondLogin	//IMessage
{
	int32 Error = 1;
	int32 SceneType = 2;
	int32 SceneId = 3;
}

message M2C_UnitNumericListUpdate // IMessage
{
	int32 RpcId = 90;
	int64 UnitID  = 1;
	repeated int32 Ks = 2;
	repeated int64 Vs = 3;
}

message M2C_UnitNumericUpdate // IMessage
{
	int32 RpcId = 90;
	int64 ActorId = 93;
	int64 UnitId = 94;
	int32 SkillId = 1;
	int32 NumericType = 2;
	int64 OldValue = 3;
	int64 NewValue = 4;
	int32 DamgeType = 5;
	int64 AttackId = 6;
}

message M2C_RoleDataBroadcast // IMessage
{
	int32 RpcId = 90;
	int32 Error = 91;
	string Message = 92;
	int32 UpdateType = 1;				//UserDataType
	string UpdateTypeValue = 2;			
	int64 UnitId = 3;
}


message C2M_GMCommand // ILocationMessage
{
	int32 RpcId = 1;
	string GMMsg = 2;
}

message ItemInfo
{
	int64 Id = 1;
	int32 ConfigId = 2;
	int32 ContainerType = 3;
	int32 Num = 4;
}

// ResponseType M2C_GetAllItem
message C2M_GetAllItem // ILocationRequest
{
	int32 RpcId = 1;
}

message M2C_GetAllItem // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	repeated ItemInfo ItemList = 4;
}

message M2C_ItemUpdateOp // IMessage
{
	ItemInfo ItemInfo = 1;
	int32 ItemOpType = 2;
}

// ResponseType M2C_SellItem
message C2M_SellItem // ILocationRequest
{
	int32 RpcId = 1;
	int64 ItemId = 2;
	int32 Num = 3;
}

message M2C_SellItem // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// ResponseType M2C_UseItem
message C2M_UseItem // ILocationRequest
{
	int32 RpcId = 1;
	int64 ItemId = 2;
	int32 Num = 3;
	int64 HeroId = 4;
}

message M2C_UseItem // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

message HeroInfo
{
	int64 Id = 1;
	int32 ConfigId = 2;
	int32 Lv = 3;
	int32 Exp = 4;
	int32 Star = 5;
	int32 HunShi = 6;
	map<int32,int64> Equipments = 7;
	map<int32,int64> NumericDic = 8;
}

// ResponseType M2C_GetAllHero
message C2M_GetAllHero // ILocationRequest
{
	int32 RpcId = 1;
}

message M2C_GetAllHero // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	repeated HeroInfo HeroList = 4;
	repeated int64 Formation = 5;
}

message M2C_HeroUpdateOp // IMessage
{
	HeroInfo HeroInfo = 1;
	int32 HeroOpType = 2;
}

// ResponseType M2C_SetHeroFormation
message C2M_SetHeroFormation // ILocationRequest
{
	int32 RpcId = 1;
	int32 OpType = 2; //0上阵 1下阵
	int64 HeroId = 3;
	int32 SlotIndex = 5;
}

message M2C_SetHeroFormation // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	repeated int64 Formation = 4;
}

// ResponseType M2C_SetHeroEquipment
message C2M_SetHeroEquipment // ILocationRequest
{
	int32 RpcId = 1;
	int32 OpType = 2; //0穿上 1卸下
	int64 HeroId = 5;
	int64 ItemId = 6;
}

message M2C_SetHeroEquipment // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

message M2C_RoleDataUpdate // IMessage
{
	int32 UpdateType = 1;
	string UpdateTypeValue = 2;
	int64 UpdateValueLong = 3;
}

// ResponseType M2C_GetUserInfo
message C2M_GetUserInfo // ILocationRequest
{
	int32 RpcId = 1;
}

message M2C_GetUserInfo // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
	string PlayerName = 4;
	int64 Gold = 5;
	int64 Diamond = 6;
	int64 Exp = 7;
	int32 Lv = 8;
}

// ResponseType M2C_SetTimeScale
message C2M_SetTimeScale // ILocationRequest
{
	int32 RpcId = 1;
	float TimeScale = 2;
}

message M2C_SetTimeScale // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

message M2C_UpdateTimeScale // IMessage
{
	int32 Error = 1;
	float TimeScale = 2;
}

// ResponseType M2C_EnterBossRoom
message C2M_EnterBossRoom // ILocationRequest
{
	int32 RpcId = 1;
}

message M2C_EnterBossRoom // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

// ResponseType M2C_TryUseSkill
message C2M_TryUseSkill // ILocationRequest
{
	int32 RpcId = 1;
	int32 SkillConfigId = 2;
	int64 TargetId = 3;
	float Angle = 4;
	Unity.Mathematics.float3 Position = 5;
}

message M2C_TryUseSkill // ILocationResponse
{
	int32 RpcId = 1;
	int32 Error = 2;
	string Message = 3;
}

message M2C_OnUseSkill // IMessage
{
	int64 UnitId = 1;
	int32 SkillConfigId = 2;
	int64 TargetId = 3;
	float Angle = 4;
	Unity.Mathematics.float3 Position = 5;
	float CD = 6;
	float PublicCD = 7;
}

message M2C_UnitFinishSkill // IMessage
{
	int64 UnitId = 1;
}

message M2C_UnitBuffUpdate // IMessage
{
	int32 BuffID = 1;
	int64 UnitIdBelongTo = 2;
	int32 BuffOperateType = 4; //1新增  2移除 3重置
	repeated float TargetPostion = 5;
	float BuffEndTime = 6;
	string Spellcaster = 7;
	int32 UnitType = 8;
	int32 UnitConfigId = 9;
	int32 SkillId = 10;
	int64 UnitIdFrom = 11;
}

message M2C_UnitBuffRemove // IMessage
{
	int32 BuffID = 1;
	int64 UnitIdBelongTo = 2;
}